        parameters:
              knob_value:
                type: int
                default: 0
              current_limit:
                 type: int
                 default: 30
              speed :
                type: int
                default: 200000
              sleep_time:
                type: int
                default: 2
