parameters:
  sample_rate:
    type: float
    default: 100
  transition_width:
    type: float
    default: 5.0
  stop_band_attenuation:
    type: float
    default: 60
  cutoff_freq:
    type: float
    default: 10.0